version: 0.1
name: NodeJS
description: NodeJS webservice automatic deployment via Github.
image: logo.jpeg
resources:
  - name: main
    type: container
    size:
      minimum: nano
      default: nano
    platform: node
    build: >
      rm -rf ./project &&
      git clone {{ repository.url }} ./project --branch {{ repository.branch }} --depth 1 &&
      cd ./project &&
      npm install &&
      {{ build }}
    start: cd ./project && {{ start }}
    https: true
triggers:
  - type: github
    repository:
      name: '{{ repository.name }}'
      branch: '{{ repository.branch }}'
inputs:
  - name: repository
    label: Github Repository
    type: github
    required: true
    description: Repository containing the source code.
  - name: build
    label: Build Command
    type: text
    default: npm run build
    description: Command to execute when building the service.
    validation:
      message: only number are accepted.
      regex: ^[0-9]+$
  - name: start
    label: Start Command
    type: text
    default: npm start
    description: Command to execute when starting the service.
    validation:
      message: only number are accepted.
      regex: ^[0-9]+$
